# Generated by Django 5.1 on 2024-08-31 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user_details',
            new_name='UserDetails',
        ),
    ]
