# Generated by Django 5.1 on 2024-09-04 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_userdetails_email_alter_userdetails_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
