# Generated by Django 5.1 on 2024-09-04 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_userdetails_last_login'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserDetails',
        ),
    ]
